
import type { Meal } from "../types/meal";
import { mealToIngredients } from "./mealToIngredients";
import { aggregateIngredients } from "./aggregateIngredients";

// Real data from TheMealDB API
const teriyakiChickenCasserole: Meal = {
  idMeal: "52772",
  strMeal: "Teriyaki Chicken Casserole",
  strIngredient1: "rice",
  strIngredient2: "chicken breast",
  strIngredient3: "broccoli",
  strIngredient4: "carrot",
  strIngredient5: "soy sauce",
  strIngredient6: "honey",
  strIngredient7: "rice vinegar",
  strIngredient8: "ginger",
  strIngredient9: "garlic",
  strIngredient10: "cornstarch",
  strIngredient11: "sesame seeds",
  strIngredient12: "green onions",
  strIngredient13: "",
  strIngredient14: "",
  strIngredient15: "",
  strIngredient16: "",
  strIngredient17: "",
  strIngredient18: "",
  strIngredient19: "",
  strIngredient20: "",
  strMeasure1: "2 cups cooked",
  strMeasure2: "2 cups shredded",
  strMeasure3: "1 cup chopped",
  strMeasure4: "1 cup shredded",
  strMeasure5: "1/2 cup",
  strMeasure6: "1/4 cup",
  strMeasure7: "2 tbsp",
  strMeasure8: "1 tsp grated",
  strMeasure9: "2 cloves minced",
  strMeasure10: "1 tbsp",
  strMeasure11: "for garnish",
  strMeasure12: "for garnish",
  strMeasure13: "",
  strMeasure14: "",
  strMeasure15: "",
  strMeasure16: "",
  strMeasure17: "",
  strMeasure18: "",
  strMeasure19: "",
  strMeasure20: "",
  strDrinkAlternate: null,
  strCategory: "Chicken",
  strArea: "Japanese",
  strInstructions: "...",
  strMealThumb: "...",
  strTags: "...",
  strYoutube: "...",
  strSource: null,
  strImageSource: null,
  strCreativeCommonsConfirmed: null,
  dateModified: null,
};

// Mock data with overlapping ingredients
const beefStirFry: Meal = {
  idMeal: "52773",
  strMeal: "Beef Stir-Fry",
  strIngredient1: "beef",
  strIngredient2: "bell pepper",
  strIngredient3: "soy sauce",
  strIngredient4: "ginger",
  strIngredient5: "garlic",
  strIngredient6: "rice",
  strIngredient7: "",
  strIngredient8: "",
  strIngredient9: "",
  strIngredient10: "",
  strIngredient11: "",
  strIngredient12: "",
  strIngredient13: "",
  strIngredient14: "",
  strIngredient15: "",
  strIngredient16: "",
  strIngredient17: "",
  strIngredient18: "",
  strIngredient19: "",
  strIngredient20: "",
  strMeasure1: "500g sliced",
  strMeasure2: "1 large",
  strMeasure3: "1/4 cup",
  strMeasure4: "1 tbsp grated",
  strMeasure5: "3 cloves minced",
  strMeasure6: "2 cups cooked",
  strMeasure7: "",
  strMeasure8: "",
  strMeasure9: "",
  strMeasure10: "",
  strMeasure11: "",
  strMeasure12: "",
  strMeasure13: "",
  strMeasure14: "",
  strMeasure15: "",
  strMeasure16: "",
  strMeasure17: "",
  strMeasure18: "",
  strMeasure19: "",
  strMeasure20: "",
  strDrinkAlternate: null,
  strCategory: "Beef",
  strArea: "Chinese",
  strInstructions: "...",
  strMealThumb: "...",
  strTags: "...",
  strYoutube: "...",
  strSource: null,
  strImageSource: null,
  strCreativeCommonsConfirmed: null,
  dateModified: null,
};

console.log("--- Testing mealToIngredients on a single meal (Teriyaki Chicken Casserole) ---");
const ingredientsFromOneMeal = mealToIngredients(teriyakiChickenCasserole);
console.log(ingredientsFromOneMeal);

console.log("\n--- Testing aggregateIngredients on two meals ---");
const allMeals = [teriyakiChickenCasserole, beefStirFry];
const aggregated = aggregateIngredients(allMeals);
console.log(aggregated);
